# Generated by Django 4.0.2 on 2022-04-05 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mane',
            new_name='name',
        ),
    ]
